# Generated by Django 4.2 on 2024-11-17 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '유저',
                'db_table': 'custom_user',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateTimeField(null=True)),
                ('event_location', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': '이벤트',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '멤버',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voted_places', models.JSONField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member')),
            ],
            options={
                'verbose_name': '투표',
                'db_table': 'vote',
            },
        ),
        migrations.CreateModel(
            name='MeetingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member')),
            ],
            options={
                'verbose_name': '모임',
                'db_table': 'meeting_group',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.meetinggroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member')),
            ],
            options={
                'verbose_name': '모임 멤버',
                'db_table': 'group_member',
            },
        ),
        migrations.CreateModel(
            name='EventLocationSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_places', models.JSONField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member')),
            ],
            options={
                'verbose_name': '이벤트 장소 선택',
                'db_table': 'event_location_selection',
            },
        ),
        migrations.CreateModel(
            name='EventDateSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_dates', models.JSONField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member')),
            ],
            options={
                'verbose_name': '이벤트 날짜 선택',
                'db_table': 'event_data_selection',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.member'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.meetinggroup'),
        ),
    ]
