# Generated by Django 4.2 on 2024-11-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.member'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_places',
            field=models.CharField(max_length=500),
        ),
    ]
