# Generated by Django 4.2 on 2024-11-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_membership_group'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('member', 'group'), name='unique_membership'),
        ),
    ]
