# Generated by Django 4.2 on 2024-11-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membership_unique_membership'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventdateselection',
            constraint=models.UniqueConstraint(fields=('member', 'event'), name='unique_member_event_selection'),
        ),
    ]
